### ISSUE TITLE
This Application Needs New Data Added to [name of layer]

### ISSUE THREAD

**Issue by JCastleton** [UGS-GIO/geohaz#106]
### Name of Existing Layer (as it appears in the application)

Flood and Debris-Flow Hazard

### Folder path of data

M:\Shared drives\UGS_Hazards_MapPortal\Hazards Portal

### Why do you feel this application needs what you're requesting?

@jjhi11 @nmpayne Please REMOVE Flood and Debris Flow from the online app Statewide. Please make sure it does not get re-published during future updates. We will be mapping this hazard differently and will have new data to replace it shortly. 

### Who has reviewed your database so far (e.g. Schema, Field Types, Topology, etc.)?

This is a result of discussion with the hazards team and Steve Bowman who has approved. 

### Who has reviewed your science and grammar so far?

No review needed

**Comment by marshallrobinson** [comment]
Thanks @JCastleton, this has been added to Nate's queue. He is out of town this week so realistically, he won't be able to work on this for another week or two after he is caught up. Thanks

**Comment by nmpayne** [comment]
The data has been removed from the webmap table of contents. We are still working on completely removing from the report tool and mapped areas.

**Comment by nmpayne** [comment]
Flood and Debris Flow Hazard is no longer on the app.
