### ISSUE TITLE
Add new Cache Valley fault mapping to Geologic Hazards Portal

### ISSUE THREAD

**Issue by AHiscock** [UGS-GIO/geohaz#115]
### Name of Existing Layer (as it appears in the application)

Hazardous (Quaternary Age) Faults, Surface Fault Rupture Special-Study Zones, Mapped Areas

### Folder path of data

M:\Shared drives\UGS_Shared\AHiscock\Cache Valley Fault Mapping\RI Review\GIS

### Why do you feel this application needs what you're requesting?

Need to add updated fault mapping for Cache Valley. The publication (UGS RI-286) is now through review and with editiorial. The pub will contain a GIS Database with the fault mapping and special study zones, in addtion to this data being available through the Geologic Hazards Portal. 

The data for this update is located at \Shared drives\UGS_Shared\AHiscock\Cache Valley Fault Mapping\RI Review\GIS in a File Geodatabase named "CacheValley_RI286_GIS.gdb". The following feature classes in this geodatabase are to be used for updating the hazards portal:

- CV_RI_FaultMapping - for updating the "Hazardous (Quaternary age) Faults" layer in the haz portal 
- CV_RI_ProjectExtent - for updating/appending to the "Mapped Areas" layer in the haz portal 
- CV_RI_SSZ - for updating/appending to the "Surface Fault Rupture Special Study Zones" layer in the haz portal

For updating the faults layer, you can use the "CV_RI_ProjectExtent" polygon to select which faults to update in the haz portal. The existing faults in the haz portal which lie within this extent polygon can be deleted out and replaced with the new fault mapping provided (CV_RI_FaultMapping). We've updated fault mapping in the haz portal using this method in the past, and it seems to work well. We've also replaced/updated fault mapping using the FaultNum metadata field in the fault mapping feature class in the past. Here's a list of the FaultNum's we'll be replacing in the portal:

- 2521a
- 2521b
- 2521c
- 2352a
- 2352b
- 2352c
- 2370
- 2378
- 2373

Additionally, FaultNum 2374 is officially deleted. We've merged those faults into fault num 2521c. 
For the report URL or report ID link in the haz portal, the DOI link for this final publication is https://doi.org/10.34191/RI-286. It's not live yet, but Jen gave me the DOI link already. 

Hopefully this all makes sense. Please let me know if you have any questions.

### Who has reviewed your database so far (e.g. Schema, Field Types, Topology, etc.)?

Kristi Rasmussen has reviewed the data (topology, fields, etc) - @kristirUGS 

### Who has reviewed your science and grammar so far?

Steve Bowman, Steph Carney (@geowomansteph), and Mike Hylland have reviewed the science/grammer.

**Comment by marshallrobinson** [comment]
added, reviewed, and LIVE 👍🏻
