### ISSUE TITLE
Liquefaction not showing up everywhere

### ISSUE THREAD

**Issue by marshallrobinson** [UGS-GIO/geohaz#14]
<h3>Legend/Popups</h3>

**Liquefaction Susceptibility**
- [ ] Not showing up for anything but SL valley
- [ ] St. George should have it
- [ ] GCNRA (Glen Canyon) should have it (If there is no mapping here, then please remove Liquefaction Susceptibility from the list of Mapped Hazards in the Mapped Areas feature class)

**Comment by marthajensen** [comment]
The AGOL feature service is showing Liquefaction susc. in a webmap. I tried some things - hoping they would get the St. George data to work in the app - I increased the maxRecordCount to 100,000 - the data still did not appear.  I maximized the CDN as well. The data is still not showing in St George or GCNRA

**Comment by marshallrobinson** [comment]
This was fixed by addressing the rendering field in the code.
