### ISSUE TITLE
V2 Release Issue

### ISSUE THREAD

**Issue by JCastleton** [UGS-GIO/geohaz#20]
The schema for Surface Fault Rupture Hazard is incorrect in the attribute table headings. It should be SFRHazardUnit, SFRUpdateDate, not SFZ. Everything else is correct in this dataset. 
![SFR](https://user-images.githubusercontent.com/63422273/80641399-0a9ffe00-8a22-11ea-83a7-d8fbd5927512.png)

We will map with this schema for now, until it can be fixed without breaking anything.

**Comment by JCastleton** [comment]
The incorrect field name is just an alias the actual field name is correct. This may not be an issue

**Comment by marthajensen** [comment]
This is fixed. I am going to close the issue
