### ISSUE TITLE
Mapped Areas data fix for Glen Canyon polygon

### ISSUE THREAD

**Issue by marshallrobinson** [UGS-GIO/geohaz#27]
- [x] The report id needs changed to SS-166.
- [x] The mapped hazards need to be (match formatting of other mapped areas though): 
(1) flooding
and debris flows, 
(2) rockfall, 
(3) landslides, 
(4) soils susceptible to piping and erosion, 
(5) gypsiferous soil and rock, 
(6) expansive soil and rock, 
(7) collapsible soil, 
(8) surface faulting, 
(9) liquefaction, and 
(10) indoor radon potential

**Comment by gordondouglass** [comment]
Fixed. Geologic Radon Susceptibility does not exist as a separate hazard. Think it was combined with something else. Question for Jessica....

**Comment by marshallrobinson** [comment]
Right: Gypsiferous soil and rock is Soluble Soil and Rock Susceptibility now...please stick to that

**Comment by gordondouglass** [comment]
OK Updated with Soluble Soil and Rock Susceptibility should be good to go

**Comment by marthajensen** [comment]
The data has been republished and this issue is fixed now.
