### ISSUE TITLE
Flood Hazard in Legend

### ISSUE THREAD

**Issue by marshallrobinson** [UGS-GIO/geohaz#28]
Change "Flood Hazard" in legend to "Flood and Debris-Flow Hazard" to match popup titles.

**Comment by marshallrobinson** [comment]
Mapped Hazards in Mapped areas popups need to match. @JCastleton, how would you like to proceed? Tyler's publication keeps calling this "Flood and Debris-Flow Hazard" as well.

**Comment by JCastleton** [comment]
It should be flood and debris-flow hazard

**Comment by marshallrobinson** [comment]
- [ ] Additionally, Mapped Areas popups that list Mapped Hazards and the Report Generator titles need to match this wording as well as they are also only calling it Flood Hazard instead of Flood and Debris-Flow Hazard.

Also, @JCastleton, which wording is correct: Geologic Radon Hazard or Geologic Radon Susceptibility? This also needs to be straightened out across the legend/mapped areas/report generator.

**Comment by marshallrobinson** [comment]
@JCastleton Geologic Radon Hazard/Susc is referred to as "Radon Hazard" in Tyler's publication.

**Comment by JCastleton** [comment]
It is Geologic Radon Susceptibilty
