### ISSUE TITLE
Create database design/schema document

### ISSUE THREAD

**Issue by marshallrobinson** [UGS-GIO/geohaz#3]
Gordon, Jessica, and Martha need to set up database together.
Things to include in document:
- [x] Database design
- [x] Database name
- [x] Relates/Joins 
- [x] Field names
- [x] Field types
- [x] Domains (if any)
- [x] Permissions
- [ ] Update schedule

Get final sign-off by Martha & post document to github.

**Comment by marthajensen** [comment]
Working on this -- https://github.com/UGS-GIO/geohaz/wiki/Database-documentation
