### ISSUE TITLE
Quaternary faults get duplicated in report summary as "Earthquake" Mapped Geologic Hazards

### ISSUE THREAD

**Issue by jjhi11** [UGS-GIO/geohaz#36]
Can we change the HazardName of the qfaults in the HazardUnitTextTable from "Earthquake" to "Quaternary Fault"?  It would be more descriptive then in the report and help with the heading of the qfaults area of the report.

**Comment by marthajensen** [comment]
@JCastleton @emkleb I can make this change - Are you Okay with it?

**Comment by JCastleton** [comment]
Yes please!

**Comment by marthajensen** [comment]
will do. Thanks @JCastleton

**Comment by gordondouglass** [comment]
In the HazardUnitTextTable if you need help let me know

**Comment by marthajensen** [comment]
The data has been changed in the HazardUnitTextTable -
