### ISSUE TITLE
Review and Usability notes from BK

### ISSUE THREAD

**Issue by bkeach2** [UGS-GIO/geohaz#38]
App works really great. Love the look and feel. Performance was fine on hi-speed wifi in my home in Hurricane. A few comments and suggestions, if not too late for this version. I suspect they are ones you have already thought of and discussed.

Need an introduction to the app, with comments on how to use. Which mouse buttons to use, how to pull information from the map, etc. An experienced will be fine. A novice home owner may be lost without some ground rules.

Need a comment, in simple language, that not all areas have been mapped. Just because they don't find a hazard on the map, doesn't mean there isn't one in their area. Should be in the app and in the reports. The standard disclosure in we use is more directed at professionals and lawyers. 

I couldn't find a way to display location information. ie. XY, lat long. Also couldn't find any in the generated report.  

When I used the Find my location feature, it took me a location about 2 miles due east. i suspect this is a google issue.

Some displays and reports took longer to generate than others. I suspect this is due to the amount of data being gathered. Would be good to include advice to be patient in the App introduction. Many users live a "I want it now!!!" world and may not wait for the full data display.

Just some thoughts on a project well done. Thanks to all.

**Comment by marshallrobinson** [comment]
Thanks for the review comments. I have created new issues to (hopefully) better track each comment.
