### ISSUE TITLE
Replace flood hazard mapping for Magna, Copperton, Tickville

### ISSUE THREAD

**Issue by JCastleton** [UGS-GIO/geohaz#54]
Replace the flood hazard mapping in the final master geodatabase for Magna Copperton and Tickville springs. The new mapping is located here: G:\Shared drives\UGS_Hazards_Geotech\UHMA\Utah County\Quads\Multi Quad Hazard Mapping\MultiQuadMapping.gdb
Feature Class:	Flood_Hazard

This will fix the empty polygons and correctly identify them as undefined. 

@gordondouglass 
@marthajensen

**Comment by gordondouglass** [comment]
Done

**Comment by JCastleton** [comment]
Flood mapping has been replaced for Northern and Southern Utah

**Comment by marthajensen** [comment]
@marshallrobinson this is done and ready for review. The "Undefined Flood Hazard" polygons were added to Magna, Copperton, and Tickville
