### ISSUE TITLE
Move all data for the online app and hazard mapping to one location

### ISSUE THREAD

**Issue by JCastleton** [UGS-GIO/geohaz#55]
Move all data from the L drive and the G:AGRC folder to 

G:\Shared drives\UGS_Hazards_Geotech\Geologic Hazards Online Data

Name items with descriptive text instead of dates. 

Delete/archive all old data in that folder. 

Delete sata from the L drive and from the Hazards AGRC folder when the data migration is complete. 

@gordondouglass @marthajensen

**Comment by gordondouglass** [comment]
Moved  the data, put the geodatabase and the MXD here G:\Shared drives\UGS_Hazards_Geotech\Geologic Hazards Online Data
Waiting to delete until we make sure all is OK
