### ISSUE TITLE
Replace About Panel and other text

### ISSUE THREAD

**Issue by JCastleton** [UGS-GIO/geohaz#7]
Text for the About Panel and other areas. Also located here in Static Text_MASTER

About Panel

The Utah Geologic Hazards Database contains post-2008 UGS geologic hazard map data and data from other sources for parts of Utah. These data address earthquake, flood, landslide, and problem soil and rock hazards. Data maintained by other agencies, such as dam failure inundation and earthquake epicenters, are also available to view. This web mapping application is intended to provide planners, local government officials, property owners, developers, engineers, geologists, design professionals, and the public with information on the type, location, and relative severity of geologic hazards that may impact existing and future infrastructure and development. The data also provide information that may be used for emergency response and recovery planning and community risk assessment for existing development and infrastructure.  

Areas with comprehensive geologic hazard map data are shown with red polygons.  Areas where comprehensive map data are not available but some hazard data exists are shown in blue polygons. Statewide data for hazardous (Quaternary age) faults, earthquake epicenters, and a legacy compilation of landslides are also available.  Limited, comprehensive geologic hazard map data are available for the remaining hazards listed in the Legend.  Hazard map layers, along with available lidar elevation data, can be enabled in the Legend by clicking on the eye symbol.  Map layer units describing the hazard relative severity are also shown in the Legend.  The absence of data does not imply that no geologic hazard or hazards exist. Additional geologic hazard mapping is on-going and will be added to the database as it is finalized.  

Related Information 
For more information, see https://geology.utah.gov/hazards or contact the UGS.  

Database Contents Panel :
The Geologic Hazards Mapping Database contains geologic hazard information and data from the Utah Geological Survey (UGS) and other sources. The database is periodically updated to incorporate the results of new mapping. Detailed geologic hazard mapping is available for limited areas and for specific hazards in Utah and additional mapping is ongoing.

The Utah database exists as an attributed geographic information system (GIS) feature class in the State Geographic Information Database (SGID), and is available through the Utah Automated Geographic Reference Center (AGRC). Users can access full data reports for individual hazards by clicking on the “Detailed Report” link in pop-up window. These reports are not a substitute for a site-specific geologic hazards and geotechnical engineering investigation by a qualified, Utah-licensed consultant.  These investigations provide valuable information on the site geologic conditions that may affect or be affected by development, as well as the type and severity of geologic hazards at a site and recommend solutions to mitigate the effects and costs of the hazards, both at the time of construction and over the life of the development.  See your local city or county building department for details on these investigations and UGS Circular 122 https://ugspub.nr.utah.gov/publications/circular/c-122.pdf).

Background & Acknowledgements Panel:
In 2008, the Utah Geological Survey Geologic Hazards Mapping Initiative was created with funding from the Utah Legislature to map geologic hazards in areas of existing and future development. This mapping is focused on identifying hazards for an entire 7.5′ quadrangle at 1:24,000 scale, instead of single hazard maps of large regional areas. The geologic-hazard maps address hazards associated with earthquakes, landslides, flooding, debris flows, indoor radon, shallow groundwater, rockfall, and problem soils and rocks. The initiative will provide planners, local officials, property owners, developers, engineers, geologists, design professionals, and the interested public with information on the type and location of critical geologic hazards that may impact existing and future development.

Acknowledgments
Hazard mapping is a multidisciplinary cooperative collaboration.  We thank Scott Davis, Nathan Kota, Steve Gourley, and Jake Adam with the Utah Automated Geographic Reference Center (AGRC) for assistance and programming in the creation of the online web mapping application. Steve Bowman and Jessica Castleton (UGS) helped develop the schema and reporting format used in the current database. Marshall Robinson, Jay Hill, and Martha Jensen (UGS) and Corey Unger (former UGS) did web design and programming for the interactive map. UGS GIS analysts Gordon Douglass contributed substantially at various stages of development of the database. We thank the hazard mappers in the UGS hazard department for providing high quality hazard maps.  

Disclaimer Panel:
Although this product represents the work of professional scientists, the Utah Department of Natural Resources, Utah Geological Survey, makes no warranty, expressed or implied, regarding its suitability for a particular use. The Utah Department of Natural Resources, Utah Geological Survey, shall not be liable under any circumstances for any direct, indirect, special, incidental, or consequential damages with respect to claims by users of this product. The Utah Geological Survey does not guarantee accuracy or completeness of the data.
The Utah Geologic Hazards Database contains geologic hazard information and data from the Utah Geological Survey (UGS) and other sources for the area of interest shown on the map below and can be used to identify mapped geologic hazards in an area, understand what the hazards are, and some potential ways to mitigate them.
 The database is periodically updated to incorporate the results of new mapping and/or updated mapping due to updated data and/or methodology; however, more-detailed fault traces and paleoseismic information may be available in recently published geologic maps and reports, so the database should not be considered exhaustive.
Locations of mapped geologic hazards should always be considered approximate.
The locational accuracy of  hazards on the maps vary, and spatial error can be substantial when viewing structures at high zoom levels that were originally mapped at small scales. Therefore, the locations of hazards on the map should be considered approximate. Depending on the ultimate needs of the user, a site-specific investigation by a qualified Utah-licensed Professional Geologist may be required to accurately characterize the hazards at a particular site.

**Comment by JCastleton** [comment]
G:\Shared drives\UGS_AGRC_Projects\Hazards Application
Located Here

**Comment by JCastleton** [comment]
Still seeing the old text online do I need a new link?

**Comment by jjhi11** [comment]
No it hasnt been uploaded to the server yet. Marshall is reviewing now.

**Comment by marshallrobinson** [comment]
Nope, I'm reviewing it now. @JCastleton , did you mean for the link to the AGRC to go away?

**Comment by JCastleton** [comment]
ok phew. I don't think so? Where was it?

**Comment by marshallrobinson** [comment]
In the database contents panel

**Comment by JCastleton** [comment]
What I copied and pasted above did not retain the code, please use the Static Text_MASTER - CODED version word doc here G:\Shared drives\UGS_AGRC_Projects\Hazards Application
The link should stay

**Comment by marshallrobinson** [comment]
https://github.com/UGS-GIO/geohaz/wiki/About-Panel-(for-review) is the github location for what's currently in the app's panels.
