### ISSUE TITLE
BUG: Quarternary faults layer is not working 

### ISSUE THREAD

**Issue by marshallrobinson** [UGS-GIO/geohaz#80]
### What happened?

1. It does not turn on 
2.
3.

### What did you expect to happen?

It should turn on 

### Browser Version

Chrome, Firefox, safari

**Comment by marshallrobinson** [comment]
@emkleb I'm tagging you here in case you'd like to track progress

**Comment by jjhi11** [comment]
@marthajensen 
Seems to be the layer causing issues. This uses the "with labels" feature layer here. 
https://webmaps.geology.utah.gov/arcgis/rest/services/Hazards#:~:text=Hazards/quaternary_faults_with_labels
I can't get it to load from the end point.

**Comment by marthajensen** [comment]
@jjhill - Ya it seems broken for some reason. I am going to delete the layer on ArcGIS Server and publish a new one with the same exact name.  I can't overwrite the current one since something is messed up on the Server end of things. I'll comment here when it's republished

**Comment by marthajensen** [comment]
@emkleb @marshallrobinson @jjhi11 

I republished the data and the app seems to be working fine. Please comment here if you see any issues
