### ISSUE TITLE
Incorrect Report ID in Mapped Areas

### ISSUE THREAD

**Issue by marthajensen** [UGS-GIO/geohaz#82]
### What happened?

From Adam McKean: 

When you click on Tickville Springs quadrangle it says the correct name but incorrect report ID. Should be SS-163, not OFR-500. See the screenshot below.
![image (9)](https://user-images.githubusercontent.com/11522897/191595239-661da48d-800d-46bc-a43c-8bb0038be61c.png)

### What did you expect to happen?

The report to be SS-163

### Browser Version

Chrome Version 96.0.4664.45 (Official Build) (64-bit)

**Comment by marshallrobinson** [comment]
fixed
