### ISSUE TITLE
This Application Needs New Data Added to [name of layer]

### ISSUE THREAD

**Issue by JCastleton** [UGS-GIO/geohaz#87]
### Name of Existing Layer (as it appears in the application)

Areas not mapped within project areas

### Folder path of data

G:\Shared drives\UGS_Hazards_Geotech\Geologic Hazards Online Data\Working and editing geodatabase

### Why do you feel this application needs what you're requesting?

The areas not mapped is correct in the editing version and not the live version. Kristy will copy the correct version to the final live version and let @jjhi11 when it is ready to be published. 
@mar

### Who has reviewed your database so far (e.g. Schema, Field Types, Topology, etc.)?

This feature class has been reviewed

### Who has reviewed your science and grammar so far?

There is grammar for this request

**Comment by JCastleton** [comment]
adding @kristirUGS

**Comment by kristirUGS** [comment]
Areas Not Mapped has been updated.  Please update the portal.
