### ISSUE TITLE
This Application Needs New Data Added to Caliche Hazard

### ISSUE THREAD

**Issue by kristirUGS** [UGS-GIO/geohaz#89]
### Name of Existing Layer (as it appears in the application)

Caliche Hazard

### Folder path of data

M:\Shared drives\UGS_Hazards_Geotech\Geologic Hazards Online Data\Working and editing geodatabase

### Why do you feel this application needs what you're requesting?

Please update the portal with the edits in the Caliche Hazard layer.  

### Who has reviewed your database so far (e.g. Schema, Field Types, Topology, etc.)?

Reviewed by Tyler Knudsen

### Who has reviewed your science and grammar so far?

NA

**Comment by kristirUGS** [comment]
@nmpayne

**Comment by Tyler-Knudsen** [comment]
@marshallrobinson I approve of these changes to the Caliche layer
