### ISSUE TITLE
Shallow Bedrock Potential symbolized with two "Hard" categories

### ISSUE THREAD

**Issue by marthajensen** [UGS-GIO/geohaz#9]
The Problem Soil and Rock Hazards - Shallow Bedrock Potential has two "Hard" categories in the Legend of the application. See below:

![image](https://user-images.githubusercontent.com/11522897/80152007-29ad1480-8578-11ea-88bc-f8be3674f1d8.png)

The MXD feeding the application is symbolizing two values for the Hard category, both Hsbp and HDsbp.  See screenshot below:

![image](https://user-images.githubusercontent.com/11522897/80152122-595c1c80-8578-11ea-972d-b1474cfe0ac7.png)

The fill color recipes (RGB) for the categories are as follows:
Hard:   168-56-0
Soft:    255-170-0
Buried:  233-255-190
Deep: 190-255-232

All had a 0.4 black (0-0-0) stroke on them

**Comment by jjhi11** [comment]
Fixed with a custom renderer in the code.

**Comment by marthajensen** [comment]
Jess fixed the Shallow Bedrock Potential in the mxd - it was symbolized on two attributes - one of which no longer exists in the attribute table

map.js
the var rendererBedrockPot (line 668), label "Hard"  - the value (on line 673) needs to be changed to just "Hsbp"

"HDsbp" needs to be removed from the value field (on line 673)
