### ISSUE TITLE
This Application Needs New Data Added to Collapsible Soil Susceptibility

### ISSUE THREAD

**Issue by kristirUGS** [UGS-GIO/geohaz#90]
### Name of Existing Layer (as it appears in the application)

Collapsible Soil Susceptibiliby

### Folder path of data

M:\Shared drives\UGS_Hazards_Geotech\Geologic Hazards Online Data\Working and editing geodatabase

### Why do you feel this application needs what you're requesting?

Update changes made for topology errors. 

### Who has reviewed your database so far (e.g. Schema, Field Types, Topology, etc.)?

Tyler Knudsen

### Who has reviewed your science and grammar so far?

NA

**Comment by kristirUGS** [comment]
@nmpayne

**Comment by marshallrobinson** [comment]
@kristirUGS Thanks for submitting this. Is there any science or grammar to review? Was the science (e.g. accuracy of GIS, descriptive text of hazards inside the attribute table(s)) already checked by Tyler as part of his database review?

**Comment by kristirUGS** [comment]
@Tyler-Knudsen Please approve updates to topology and let @marshallrobinson know when it is approved.

**Comment by Tyler-Knudsen** [comment]
@marshallrobinson I approve of these changes to the Collapsible Soil layer
