### ISSUE TITLE
This Application Needs a New Layer(s) - Piping_and_Erosion_Susceptibility

### ISSUE THREAD

**Issue by kristirUGS** [UGS-GIO/geohaz#91]
### Why do you feel this application needs what you're requesting?

Topology is completed with minor edits to remove gaps.  

### Describe the layer(s) you'd like to add

Piping_and_Erosion_Susceptibility - layer in gdb labeled as ForUpdate is ready to go.  

### Popup Formatting

Please keep formatting as is in the portal.  Only fixing polygons with gaps.  

### Who has reviewed your database so far? (e.g. Schema, Field Types, Topology, etc.)

Tyler Knudsen 

### Who has reviewed your science and grammar so far for both your data and application panels?

NA

### Copy/paste all text for application panels here (e.g. About, Supplemental Data, Explanation)

About Panel:
Suplemental Data:
Explanation:

### Folder path of data

M:\Shared drives\UGS_Hazards_Geotech\Geologic Hazards Online Data\Working and editing geodatabase\GeologicHazards_Review.gdb

**Comment by kristirUGS** [comment]
@nmpayne

**Comment by marshallrobinson** [comment]
@kristirUGS Thanks for submitting this. Is there any science or grammar to review? Was the science (e.g. accuracy of GIS, descriptive text of hazards inside the attribute table(s)) already checked by Tyler as part of his database review?

**Comment by Tyler-Knudsen** [comment]
@marshallrobinson No grammar changes to descriptive text. Kristi just cleaned up GIS gaps and minor mismatches with underlying geology, which I have reviewed and approve of.
