### ISSUE TITLE
This Application Needs New Data Added to Expansive Soil and Rock

### ISSUE THREAD

**Issue by kristirUGS** [UGS-GIO/geohaz#92]
### Name of Existing Layer (as it appears in the application)

Expansive_Soil_and_Rock_Susceptibility

### Folder path of data

M:\Shared drives\UGS_Hazards_Geotech\Geologic Hazards Online Data\Working and editing geodatabase\GeologicHazards_Review.gdb

### Why do you feel this application needs what you're requesting?

Edits made through topology and mapping clean-up.  Replace with version labeled with ForUpdate

### Who has reviewed your database so far (e.g. Schema, Field Types, Topology, etc.)?

Tyler Knudsen

### Who has reviewed your science and grammar so far?

NA

**Comment by kristirUGS** [comment]
@nmpayne

**Comment by marshallrobinson** [comment]
@kristirUGS Thanks for submitting this. Is there any science or grammar to review? Was the science (e.g. accuracy of GIS, descriptive text of hazards inside the attribute table(s)) already checked by Tyler as part of his database review?

**Comment by nmpayne** [comment]
@Tyler-Knudsen This updated data is ready to be added to portal as soon as it's reviewed.

**Comment by Tyler-Knudsen** [comment]
@nmpayne I have reviewed the updated Expansive soil and rock layer and approve
