### ISSUE TITLE
This Application Needs New Data Added to [Soluble Soil and Rock Susceptibility]

### ISSUE THREAD

**Issue by kristirUGS** [UGS-GIO/geohaz#93]
### Name of Existing Layer (as it appears in the application)

Soluble Soil and Rock Susceptibility

### Folder path of data

M:\Shared drives\UGS_Hazards_Geotech\Geologic Hazards Online Data\Working and editing geodatabase\GeologicHazards_Review.gdb

### Why do you feel this application needs what you're requesting?

Updating mapping with corrected topology. 

### Who has reviewed your database so far (e.g. Schema, Field Types, Topology, etc.)?

@Tyler-Knudsen, Please review for @marshallrobinson to update on hazard portal.  Topology corrected, edited Qac along southeast of St Geo Airport.  No changes made to attributes.  Please let Marshall know when this approved. 

### Who has reviewed your science and grammar so far?

NA on Grammar, @Tyler-Knudsen to review

**Comment by Tyler-Knudsen** [comment]
@nmpayne @marshallrobinson I have reviewed the updated soluble soil & rock data and approve
