### ISSUE TITLE
This Application Needs New Data Added to Wind_Blown_Sand_Susceptibility

### ISSUE THREAD

**Issue by kristirUGS** [UGS-GIO/geohaz#94]
### Name of Existing Layer (as it appears in the application)

Wind Blown Sand Susceptibility

### Folder path of data

M:\Shared drives\UGS_Hazards_Geotech\Geologic Hazards Online Data\Working and editing geodatabase\GeologicHazards_Review.gdb

### Why do you feel this application needs what you're requesting?

Update layer for topology corrections.  No changes to attribute tables.  

### Who has reviewed your database so far (e.g. Schema, Field Types, Topology, etc.)?

@Tyler-Knudsen. Please review then let @marshallrobinson know layer is ready for update.  

### Who has reviewed your science and grammar so far?

No changes to grammar.

**Comment by marshallrobinson** [comment]
Thanks @Tyler-Knudsen and @kristirUGS. 

Your turn @nmpayne
