### ISSUE TITLE
This Application Needs New Data Added to Flood and Debris-Flow Hzards

### ISSUE THREAD

**Issue by kristirUGS** [UGS-GIO/geohaz#96]
### Name of Existing Layer (as it appears in the application)

Flood and Debris-Flow Hazard

### Folder path of data

M:\Shared drives\UGS_Hazards_Geotech\Geologic Hazards Online Data\Working and editing geodatabase\GeologicHazards_Review.gdb

### Why do you feel this application needs what you're requesting?

Update for corrected topology to remove gaps between mapping bounds.  

### Who has reviewed your database so far (e.g. Schema, Field Types, Topology, etc.)?

@Tyler-Knudsen Please review and let @marshallrobinson know when it is approved.  Changes to this are noted in the google drive I shared previously.  Only changes are to remove gaps between mapping bounds.  

### Who has reviewed your science and grammar so far?

No change to science, grammar, or attributes.

**Comment by Tyler-Knudsen** [comment]
@nmpayne @marshallrobinson I have reviewed the updated flood hazard dataset and approve.
