### ISSUE TITLE
This Application Needs New Data Added to Liquefaction Susceptibility

### ISSUE THREAD

**Issue by kristirUGS** [UGS-GIO/geohaz#97]
### Name of Existing Layer (as it appears in the application)

Liquefaction Susceptibility

### Folder path of data

M:\Shared drives\UGS_Hazards_Geotech\Geologic Hazards Online Data\Working and editing geodatabase\GeologicHazards_Review.gdb

### Why do you feel this application needs what you're requesting?

Correcting topology errors including filling in gaps and merging like polygons.  

### Who has reviewed your database so far (e.g. Schema, Field Types, Topology, etc.)?

@Tyler-Knudsen Please review topology correction. Google document has detailed notes, only topology corrections including like polygons.  Please let @marshallrobinson know then this is approved

### Who has reviewed your science and grammar so far?

No changes to science, grammar, attributes, ect, only correcting topology

**Comment by Tyler-Knudsen** [comment]
Let's hold off on this one at the moment. I need to double check that the merged polygons are accurate.
