### ISSUE TITLE
Opacity for Geologic radon not working on the app

### ISSUE THREAD

**Issue by JCastleton** [UGS-GIO/geohaz#98]
### What happened?

1. Trying to decrease opacity for geologic radon susceptibility is not working
2. Seems to be working for other hazards
3. have tried in chrome and firefox

### What did you expect to happen?

Working on creating a figure for a presentation and the decrease opacity seems to not be working on this hazard

### Browser Version

Chrome, firefox

**Comment by nmpayne** [comment]
I tried it and get similar results. Tagging @jjhi11.

**Comment by jjhi11** [comment]
@marshallrobinson @JCastleton Should be fixed now
